# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install through go-wrapper
      env:
        GOROOT: ""
      run: ./gow version
    - name: No need to install go
      env:
        GOROOT: ""
      run: ./gow help
    - name: Set-up Environment
      env:
        GOROOT: ""
      run: ./gow printenv
  install-distribution-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add old version in go-wrapper.properties
        env:
          GOROOT: ""
        run: echo distributionUrl=https://dl.google.com/go/go1.13.10.linux-amd64.tar.gz > .go/wrapper/go-wrapper.properties
      - name: Install through go-wrapper
        env:
          GOROOT: ""
        run: ./gow version
      - name: No need to install go
        env:
          GOROOT: ""
        run: ./gow help
      - name: Set-up Environment
        env:
          GOROOT: ""
        run: ./gow printenv  
  install-version-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add old version in go-wrapper.properties
        env:
          GOROOT: ""
        run: echo goVersion=1.15.1 > .go/wrapper/go-wrapper.properties
      - name: Install through go-wrapper
        env:
          GOROOT: ""
        run: ./gow version
      - name: No need to install go
        env:
          GOROOT: ""
        run: ./gow help
      - name: Set-up Environment
        env:
          GOROOT: ""
        run: ./gow printenv
  no-install-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3
    - name: Use installed go
      run: ./gow help
    - name: Set-up Environment
      run: ./gow printenv
  install-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install through go-wrapper
      env:
        GOROOT: ""
      run: "gow.cmd version"
      shell: cmd
    - name: No need to install go
      env:
        GOROOT: ""
      run: "gow.cmd help"
      shell: cmd
    - name: Set-up Environment
      env:
        GOROOT: ""
      run: "gow.cmd printenv"
      shell: cmd
  install-distribution-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add old version in go-wrapper.properties
        env:
          GOROOT: ""
        run: echo distributionUrl=https://dl.google.com/go/go1.13.10.windows-amd64.zip > .go/wrapper/go-wrapper.properties
      - name: Install through go-wrapper
        env:
          GOROOT: ""
        run: "gow.cmd version"
        shell: cmd
      - name: No need to install go
        env:
          GOROOT: ""
        run: "gow.cmd help"
        shell: cmd
      - name: Set-up Environment
        env:
          GOROOT: ""
        run: "gow.cmd printenv"
        shell: cmd
  install-version-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add old version in go-wrapper.properties
        env:
          GOROOT: ""
        run: echo goVersion=1.15.1 > .go/wrapper/go-wrapper.properties
      - name: Install through go-wrapper
        env:
          GOROOT: ""
        run: "gow.cmd version"
        shell: cmd
      - name: No need to install go
        env:
          GOROOT: ""
        run: "gow.cmd help"
        shell: cmd
      - name: Set-up Environment
        env:
          GOROOT: ""
        run: "gow.cmd printenv"
        shell: cmd
  no-install-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3
    - name: Use installed go
      run: "gow.cmd help"
      shell: cmd
    - name: Set-up Environment
      run: "gow.cmd printenv"
      shell: cmd
